[tool.poetry]
name = "malib"
version = "0.5.0"
description = ""
authors = ["Louis Abraham <louis.abraham@yahoo.fr>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
